export const USER_OBJECT = 'USER_OBJECT';
export const USER_COLLECTION = 'USER_COLLECTION';
export const EMAILLIST_COLLECTION = 'EMAILLIST_COLLECTION';
export const CHEMICAL_COLLECTION = 'CHEMICAL_COLLECTION';
export const DISPOSED_COLLECTION = 'DISPOSED_COLLECTION';
export const FAMILY_COLLECTION = 'FAMILY_COLLECTION';
export const LOCATION_COLLECTION = 'LOCATION_COLLECTION';
export const TEMPZONES_COLLECTION = 'TEMPZONES_COLLECTION';