# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: bryansmi/flowbaseui:0.0.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      - run: npm install
      - run: npm run build

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
         
      # run tests!
      # - run: npm run unit

    # Deploy DEV 
      - deploy: 
            name: Deploy to DEV S3
            command: |
              aws s3 sync dist/ s3://flowbase-site-dev/ --delete --region us-east-2 ; echo "${CIRCLE_BRANCH} deployed to DEV."

    # Deploy QA
      - deploy: 
            name: Deploy to QA S3
            command: |
              if [ "${CIRCLE_BRANCH}" == "develop" ] || [ "${CIRCLE_BRANCH}" == "master" ];
                then aws s3 sync dist/ s3://flowbase-site-QA/ --delete --region us-east-2 ; echo "${CIRCLE_BRANCH} deployed to QA."
              else 
                echo "${CIRCLE_BRANCH} was not deployed to QA."
              fi

    # Deploy PROD
      - deploy: 
            name: Deploy to PROD S3
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ];
                then aws s3 sync dist/ s3://flowbase-site-PROD/ --delete --region us-east-2 ; echo "${CIRCLE_BRANCH} deployed to PROD."
              else 
                echo "${CIRCLE_BRANCH} was not deployed to PROD."
              fi
